### ISSUE TITLE
Explorer

### ISSUE THREAD

**Issue by emmdim** [DSG-UPC/eReuse-Blockchain#5]
@SergioMD15 
* Created a new branch called explorer, based on Typescript, React and Nextjs and currently on Drizzle (trufflesuite). (Drizzle seems to be in a quite unstable phase. Maybe not worth using it.)
* The first following steps can be achieved adapting explorer/pages/index.tsx and if necessary explorer/pages/_app.tsx. They follow the typical React logic (treat it like if nextjs didnt exist ;-)  )

Some future steps:
* [x] Create template and make code run (Node 12.13.1)
* [x] Basic Integration with Blockchain #9 
* [ ] Create  State module #11  -> (make necessary changes to smart contracts)
* [x] Create Smart Contract types #10 
* [x] Integrate Proofs #8 
* [x] Integrate Devices #7 

Open issues: 
* [ ] Investigate communication with DeviceHub #6
